### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by kartx22** [ben423423n32j14e/domoticscreens#1]
Hi is there any source code available for this repo?

**Comment by ben423423n32j14e** [comment]
Sure, give me half an hour and I'll upload it. Would be great to have some others working on the code. I've been working almost 24hrs straight on this, I think v8 was the previous APK in this repo, I've just uploaded the v12 APK. Source will be available soon!

**Comment by ben423423n32j14e** [comment]
http://deviceip:5000 to access the web interface

**Comment by ben423423n32j14e** [comment]
source has been uploaded, it uses Android API v21 Lollipop, can you test and confirm you can access the source ok?

Cheers

**Comment by ben423423n32j14e** [comment]
check again, sorry my newblet skills with Github... lol.

**Comment by kartx22** [comment]
@ben423423n32j14e Thank you very much. Source code is updated I'll compile the code & let you know weather it runs.
